version: "3.8"
services:
  web:
    build:
      context: .

    volumes:
      - ./data:/app/data

    environment:
      #      - PLEX_USERNAME=
      #      - PLEX_PASSWORD=
      #      - PLEX_SERVER_NAME=
      - PLEX_SERVER_URL=
      - PLEX_TOKEN=
      - ANILIST_TOKEN=
      - PLEX_ANIME_LIBRARIES=Anime
      - TIME_TO_RUN=17:00