version: "3.8"
services:
  plex-ani-sync:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data
    environment:
      - PLEX_URL=http://HOST_API:32400
      - PLEX_TOKEN=PLEX_TOKEN
      - ANILIST_TOKEN=ANILIST_TOKEN
