// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: cache.sql

package sqlite3Storage

import (
	"context"
)

const getCache = `-- name: GetCache :one
  SELECT id, "key", value, updated_at, expires_at FROM cache
  WHERE key = ?
  LIMIT 1
`

// GetCache retrieves a cache entry.
func (q *Queries) GetCache(ctx context.Context, key string) (Cache, error) {
	row := q.db.QueryRowContext(ctx, getCache, key)
	var i Cache
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Value,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const setCache = `-- name: SetCache :exec
  INSERT INTO cache (key, value, expires_at)
  VALUES (?, ?, ?)
  ON CONFLICT (key) DO UPDATE
  SET value = excluded.value,
      expires_at = excluded.expires_at,
      updated_at = datetime('now')
  RETURNING id, "key", value, updated_at, expires_at
`

type SetCacheParams struct {
	Key       string
	Value     string
	ExpiresAt string
}

// SetCache sets a cache entry.
func (q *Queries) SetCache(ctx context.Context, arg SetCacheParams) error {
	_, err := q.db.ExecContext(ctx, setCache, arg.Key, arg.Value, arg.ExpiresAt)
	return err
}
