// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: mapping.sql

package sqlite3Storage

import (
	"context"
)

const addMapping = `-- name: AddMapping :exec
INSERT INTO mappings (

    anime_id,
    anime_episode_start,
    anime_episode_end,
    season_id,
    season_episode_start,
    season_episode_end 
) VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(anime_id, season_id) DO UPDATE SET
    anime_episode_start = EXCLUDED.anime_episode_start,
    anime_episode_end = EXCLUDED.anime_episode_end,
    season_episode_start = EXCLUDED.season_episode_start,
    season_episode_end = EXCLUDED.season_episode_end,
    updated_at = datetime('now')
`

type AddMappingParams struct {
	AnimeID            string
	AnimeEpisodeStart  int64
	AnimeEpisodeEnd    int64
	SeasonID           string
	SeasonEpisodeStart int64
	SeasonEpisodeEnd   int64
}

// Add a mapping
func (q *Queries) AddMapping(ctx context.Context, arg AddMappingParams) error {
	_, err := q.db.ExecContext(ctx, addMapping,
		arg.AnimeID,
		arg.AnimeEpisodeStart,
		arg.AnimeEpisodeEnd,
		arg.SeasonID,
		arg.SeasonEpisodeStart,
		arg.SeasonEpisodeEnd,
	)
	return err
}

const deleteMapping = `-- name: DeleteMapping :exec
DELETE FROM mappings
WHERE id = ?
`

// Delete a mapping
func (q *Queries) DeleteMapping(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteMapping, id)
	return err
}

const getMappings = `-- name: GetMappings :many
SELECT id, anime_id, anime_episode_start, anime_episode_end, season_id, season_episode_start, season_episode_end, created_at, updated_at FROM mappings
WHERE season_id = ?
`

// Retrieve all mappings for a season
func (q *Queries) GetMappings(ctx context.Context, seasonID string) ([]Mapping, error) {
	rows, err := q.db.QueryContext(ctx, getMappings, seasonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Mapping
	for rows.Next() {
		var i Mapping
		if err := rows.Scan(
			&i.ID,
			&i.AnimeID,
			&i.AnimeEpisodeStart,
			&i.AnimeEpisodeEnd,
			&i.SeasonID,
			&i.SeasonEpisodeStart,
			&i.SeasonEpisodeEnd,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
