// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlite3Storage

import (
	"database/sql"
)

type Cache struct {
	ID        int64
	Key       string
	Value     string
	UpdatedAt string
	ExpiresAt string
}

type Mapping struct {
	ID                int64
	AnimeID           int64
	AnimeEpisodeStart int64
	AnimeEpisodeEnd   int64
	MediaID           int64
	MediaEpisodeStart int64
	MediaEpisodeEnd   int64
	CreatedAt         string
	UpdatedAt         string
}

type PlexUserLibrary struct {
	UserID     int64
	LibraryKey string
	CreatedAt  string
}

type User struct {
	ID               int64
	Name             string
	PlexUrl          string
	PlexToken        sql.NullString
	HostUrl          string
	ClientIdentifier string
	CreatedAt        string
	UpdatedAt        string
}
