// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: queries.sql

package sqlite3Storage

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :one
  INSERT INTO users (name, plex_url, plex_token, host_url, client_identifier)
  VALUES (?, ?, ?, ?, ?)
  RETURNING id, name, plex_url, plex_token, host_url, client_identifier, created_at, updated_at
`

type CreateUserParams struct {
	Name             string
	PlexUrl          string
	PlexToken        sql.NullString
	HostUrl          string
	ClientIdentifier string
}

// CreateUser creates a new user.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Name,
		arg.PlexUrl,
		arg.PlexToken,
		arg.HostUrl,
		arg.ClientIdentifier,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PlexUrl,
		&i.PlexToken,
		&i.HostUrl,
		&i.ClientIdentifier,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :one
  DELETE FROM users
  RETURNING id, name, plex_url, plex_token, host_url, client_identifier, created_at, updated_at
`

// DeleteUser deletes the user
func (q *Queries) DeleteUser(ctx context.Context) (User, error) {
	row := q.db.QueryRowContext(ctx, deleteUser)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PlexUrl,
		&i.PlexToken,
		&i.HostUrl,
		&i.ClientIdentifier,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCache = `-- name: GetCache :one
  SELECT id, "key", value, updated_at, expires_at FROM cache
  WHERE key = ?
  LIMIT 1
`

// GetCache retrieves a cache entry.
func (q *Queries) GetCache(ctx context.Context, key string) (Cache, error) {
	row := q.db.QueryRowContext(ctx, getCache, key)
	var i Cache
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Value,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
  SELECT id, name, plex_url, plex_token, host_url, client_identifier, created_at, updated_at FROM users 
  LIMIT 1
`

// GetUser retrieves the user.
func (q *Queries) GetUser(ctx context.Context) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PlexUrl,
		&i.PlexToken,
		&i.HostUrl,
		&i.ClientIdentifier,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setCache = `-- name: SetCache :exec
  INSERT INTO cache (key, value, expires_at)
  VALUES (?, ?, ?)
  ON CONFLICT (key) DO UPDATE
  SET value = ?,
      expires_at = ?,
      updated_at = datetime('now')
  RETURNING id, "key", value, updated_at, expires_at
`

type SetCacheParams struct {
	Key       string
	Value     string
	ExpiresAt string
}

// SetCache sets a cache entry.
func (q *Queries) SetCache(ctx context.Context, arg SetCacheParams) error {
	_, err := q.db.ExecContext(ctx, setCache, arg.Key, arg.Value, arg.ExpiresAt)
	return err
}

const updateUser = `-- name: UpdateUser :one
  UPDATE users
  SET name = ?,
      plex_url = ?,
      plex_token = ?,
      host_url = ?,
      updated_at = datetime('now')
  WHERE id = ?
  RETURNING id, name, plex_url, plex_token, host_url, client_identifier, created_at, updated_at
`

type UpdateUserParams struct {
	Name      string
	PlexUrl   string
	PlexToken sql.NullString
	HostUrl   string
	ID        int64
}

// UpdateUser updates a user's information.
func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.Name,
		arg.PlexUrl,
		arg.PlexToken,
		arg.HostUrl,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PlexUrl,
		&i.PlexToken,
		&i.HostUrl,
		&i.ClientIdentifier,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
