// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: user.sql

package sqlite3Storage

import (
	"context"
	"database/sql"
)

const addLibrary = `-- name: AddLibrary :exec
  INSERT INTO plex_user_libraries (user_id, library_key)
  VALUES (?, ?)
`

type AddLibraryParams struct {
	UserID     int64
	LibraryKey string
}

// AddLibraries adds selected library for a user.
func (q *Queries) AddLibrary(ctx context.Context, arg AddLibraryParams) error {
	_, err := q.db.ExecContext(ctx, addLibrary, arg.UserID, arg.LibraryKey)
	return err
}

const addUser = `-- name: AddUser :one
  INSERT INTO users (name, plex_url, plex_token, host_url, client_identifier)
  VALUES (?, ?, ?, ?, ?)
  RETURNING id, name, plex_url, plex_token, host_url, client_identifier, animelist_api_client_id, animelist_secret, animelist_token, animelist_refresh_token, created_at, updated_at
`

type AddUserParams struct {
	Name             string
	PlexUrl          string
	PlexToken        sql.NullString
	HostUrl          string
	ClientIdentifier string
}

// Creates a new user.
func (q *Queries) AddUser(ctx context.Context, arg AddUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, addUser,
		arg.Name,
		arg.PlexUrl,
		arg.PlexToken,
		arg.HostUrl,
		arg.ClientIdentifier,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PlexUrl,
		&i.PlexToken,
		&i.HostUrl,
		&i.ClientIdentifier,
		&i.AnimelistApiClientID,
		&i.AnimelistSecret,
		&i.AnimelistToken,
		&i.AnimelistRefreshToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteLibrary = `-- name: DeleteLibrary :exec
  DELETE FROM plex_user_libraries
  WHERE user_id = ? AND library_key = ?
`

type DeleteLibraryParams struct {
	UserID     int64
	LibraryKey string
}

// Delete library from user
func (q *Queries) DeleteLibrary(ctx context.Context, arg DeleteLibraryParams) error {
	_, err := q.db.ExecContext(ctx, deleteLibrary, arg.UserID, arg.LibraryKey)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
  DELETE FROM users
`

// DeleteUser deletes the user
func (q *Queries) DeleteUser(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteUser)
	return err
}

const getLibraries = `-- name: GetLibraries :many
  SELECT user_id, library_key, created_at FROM plex_user_libraries
  WHERE user_id = ?
`

// Retrieve all libraries for a user
func (q *Queries) GetLibraries(ctx context.Context, userID int64) ([]PlexUserLibrary, error) {
	rows, err := q.db.QueryContext(ctx, getLibraries, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlexUserLibrary
	for rows.Next() {
		var i PlexUserLibrary
		if err := rows.Scan(&i.UserID, &i.LibraryKey, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUser = `-- name: GetUser :many
SELECT id, name, plex_url, plex_token, host_url, client_identifier, animelist_api_client_id, animelist_secret, animelist_token, animelist_refresh_token, usr.created_at, updated_at, user_id, library_key, spl.created_at FROM (
    SELECT id, name, plex_url, plex_token, host_url, client_identifier, animelist_api_client_id, animelist_secret, animelist_token, animelist_refresh_token, created_at, updated_at FROM users
    LIMIT 1
) as usr
LEFT JOIN plex_user_libraries as spl ON spl.user_id = usr.id
`

type GetUserRow struct {
	ID                    int64
	Name                  string
	PlexUrl               string
	PlexToken             sql.NullString
	HostUrl               string
	ClientIdentifier      string
	AnimelistApiClientID  sql.NullString
	AnimelistSecret       sql.NullString
	AnimelistToken        sql.NullString
	AnimelistRefreshToken sql.NullString
	CreatedAt             string
	UpdatedAt             string
	UserID                sql.NullInt64
	LibraryKey            sql.NullString
	CreatedAt_2           sql.NullString
}

// GetUser retrieves the user.
func (q *Queries) GetUser(ctx context.Context) ([]GetUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getUser)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserRow
	for rows.Next() {
		var i GetUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PlexUrl,
			&i.PlexToken,
			&i.HostUrl,
			&i.ClientIdentifier,
			&i.AnimelistApiClientID,
			&i.AnimelistSecret,
			&i.AnimelistToken,
			&i.AnimelistRefreshToken,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.LibraryKey,
			&i.CreatedAt_2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :exec
  UPDATE users
  SET name = ?,
      plex_url = ?,
      plex_token = ?,
      host_url = ?,
      animelist_api_client_id = ?,
      animelist_secret = ?,
      animelist_token = ?,
      animelist_refresh_token = ?,
      updated_at = datetime('now')
  WHERE id = ?
`

type UpdateUserParams struct {
	Name                  string
	PlexUrl               string
	PlexToken             sql.NullString
	HostUrl               string
	AnimelistApiClientID  sql.NullString
	AnimelistSecret       sql.NullString
	AnimelistToken        sql.NullString
	AnimelistRefreshToken sql.NullString
	ID                    int64
}

// Update a user
func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser,
		arg.Name,
		arg.PlexUrl,
		arg.PlexToken,
		arg.HostUrl,
		arg.AnimelistApiClientID,
		arg.AnimelistSecret,
		arg.AnimelistToken,
		arg.AnimelistRefreshToken,
		arg.ID,
	)
	return err
}
