// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: copyfrom.go

package postgresStorage

import (
	"context"
)

// iteratorForAddLibraries implements pgx.CopyFromSource.
type iteratorForAddLibraries struct {
	rows                 []AddLibrariesParams
	skippedFirstNextCall bool
}

func (r *iteratorForAddLibraries) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForAddLibraries) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].UserID,
		r.rows[0].LibraryKey,
	}, nil
}

func (r iteratorForAddLibraries) Err() error {
	return nil
}

// AddLibraries adds selected libraries for a user.
func (q *Queries) AddLibraries(ctx context.Context, arg []AddLibrariesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"selected_plex_libraries"}, []string{"user_id", "library_key"}, &iteratorForAddLibraries{rows: arg})
}
