// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package postgresStorage

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID               int32
	Name             string
	PlexUrl          string
	PlexToken        pgtype.Text
	HostUrl          string
	ClientIdentifier string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}
